language: node_js

node_js:
  - "0.8"
  - "0.10"

services:
  - mongodb
  - elasticsearch

# blacklist
branches:
  except:
    - mysociety-deploy

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true
