language: node_js

node_js:
  - "0.10"

services:
  - elasticsearch
  - redis-server

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.8 mongodb-org-server=2.6.8 mongodb-org-shell=2.6.8 mongodb-org-mongos=2.6.8 mongodb-org-tools=2.6.8

# blacklist
branches:
  except:
    - mysociety-deploy

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true
