language: node_js

services:
  - mongodb

# blacklist
branches:
  except:
    - mysociety-deploy

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true
    skip_join: true
